<a href="https://colab.research.google.com/github/jeetu-g2-1/My_Projects/blob/main/WSAI_SummerIntern.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [17]:
#rotation matrix
matrix=np.array([[1,2,3],[2,3,4],[3,3,4]])
print(matrix)
m=len(matrix)
n=len(matrix[0])
print(n)
x=matrix[n-1,:].T
y=matrix[n-2,:].T
z=matrix[n-3,:].T
matrix=np.array([x,y,z])

[[1 2 3]
 [2 3 4]
 [3 3 4]]
3


In [16]:
matrix.T


array([[3, 2, 1],
       [3, 3, 2],
       [4, 4, 3]])

In [18]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [2, 3, 4],
                   [3, 3, 4]])

print("Original Matrix:")
print(matrix)

# Rotating 90 degrees counterclockwise three times (equivalent to 90-degree clockwise rotation)
rotated_matrix = np.rot90(matrix, k=3)

print("Rotated Matrix (k=3, same as 90-degree clockwise):")
print(rotated_matrix)


Original Matrix:
[[1 2 3]
 [2 3 4]
 [3 3 4]]
Rotated Matrix (k=3, same as 90-degree clockwise):
[[3 2 1]
 [3 3 2]
 [4 4 3]]
